# Application properties for Capstone GD project

# Configure the logging level to info for Spring Framework
logging:
  level:
    org.springframework: info

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # File Upload Preferences
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # Disable Compatibility Verifier
  cloud:
    compatibility-verifier:
      enabled: false

resource:
  file:
    url: /resources/files
    path: ${user.dir}/cloud
    allow-extension: bmp,jpg,jpeg,png,gif